name = "labs_standalone"
description = "Ada exercices for training"
version = "0.1.0-dev"

authors = ["Léo Germond"]
maintainers = ["Léo Germond <germond@adacore.com>"]
maintainers-logins = ["leogermond"]

executables = ["genericity_text_main"]
